services:
  inventory:
    build: 
      context: .
      dockerfile: .Dockerfile
    environment:
      - PORT=3002
      - KAFKA_BROKER=kafka:29092
    ports:
      - 3002:3002
    depends_on:
      - kong
    networks:
      - inventory-network
      - broker-kafka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3002" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  inventory-network:
    name: inventory-network
    driver:
      bridge